language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
script:
    - make
    - make devel
    - make install
    - make test
notifications:
    email:
        recipients:
            - jesse_cooper@codeholics.com
        on_success: never
        on_failure: always
